[package]
name = "CustomSocket_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.3", features = ["full"]}
CustomIterators = {path = "../CustomIterators"}
rand = "0.9.0-alpha.2"
lazy_static = "1.5.0"