[package]
name = "CustomSocket"
version = "0.1.0"
edition = "2021"

[dependencies]
CustomSocket_lib = {path = "CustomSocket_lib"}
CustomServer = {path = "CustomServer"}
tokio = "1.39.3"
futures = "0.3.30"

